# Generated by Django 4.1.5 on 2023-02-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_bill_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_list',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='product_list',
            name='product',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_list',
        ),
    ]
